import { ArrowRight, BookOpen, Bookmark, Clock3, FileQuestion, FileSearch, Flame, GraduationCap, LibraryBig, Target } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmptyState, PageHeader, ProgressBar } from '../../components/ui'
import { useAuth } from '../../context/AuthContext'
import { useData } from '../../context/DataContext'
import { courseCompletion, learningStats } from '../../services/progressService'

export default function DashboardPage() {
  const { user } = useAuth()
  const { data, progress, quizHistory, bookmarks, recentViews } = useData()
  const stats = learningStats(data, progress, quizHistory)
  const activeCourses = data.courses.filter((course) => progress.startedCourses.includes(course.id) && courseCompletion(course, progress) < 100)
  const name = user?.fullName?.split(' ')[0] || 'Student'
  const lastQuiz = quizHistory[0]

  return <div className="page dashboard-page">
    <PageHeader eyebrow="Study overview" title={`Welcome back, ${name}.`} description="Pick up where you left off or begin with a clean research task." actions={<Link to="/search" className="button button--secondary"><FileSearch size={17} /> Search everything</Link>} />
    <section className="dashboard-summary" aria-label="Learning summary"><div className="dashboard-summary__lead"><p>Overall progress</p><strong>{stats.overallProgress}%</strong><ProgressBar value={stats.overallProgress} /><small>{stats.lessonsCompleted} lessons completed across your catalog</small></div><div><span><Clock3 size={18} /> Study time</span><strong>{stats.studyMinutes}<small> min</small></strong></div><div><span><FileQuestion size={18} /> Quiz accuracy</span><strong>{stats.quizAccuracy}<small>%</small></strong></div><div><span><Flame size={18} /> Active days</span><strong>{new Set(progress.studySessions.map((item) => item.date)).size}</strong></div></section>

    <div className="dashboard-layout"><div className="dashboard-main"><section className="section-block"><div className="section-heading"><div><p className="eyebrow">Continue learning</p><h2>Current courses</h2></div><Link to="/courses">Browse courses <ArrowRight size={16} /></Link></div>{activeCourses.length ? <div className="course-stack">{activeCourses.slice(0, 3).map((course) => { const rate = courseCompletion(course, progress); return <Link to={`/courses/${course.id}`} className="course-row" key={course.id}><span className="course-row__icon"><GraduationCap size={21} /></span><span><small>{course.category}</small><strong>{course.title}</strong><ProgressBar value={rate} /></span><b>{rate}%</b><ArrowRight size={18} /></Link> })}</div> : <EmptyState icon={BookOpen} title="No course in progress" description={data.courses.length ? 'Open a course and start its first lesson. It will stay visible here.' : 'Your course catalog is empty. Import verified course content from Settings when it is ready.'} action={<Link to={data.courses.length ? '/courses' : '/settings'} className="button button--secondary">{data.courses.length ? 'Choose a course' : 'Open data settings'}</Link>} />}</section>
      <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Research history</p><h2>Recently viewed</h2></div><Link to="/library">Open library <ArrowRight size={16} /></Link></div>{recentViews.length ? <div className="simple-list">{recentViews.slice(0, 5).map((item) => <Link key={`${item.type}-${item.id}`} to={item.url}><span className="record-type">{item.type}</span><strong>{item.title}</strong><small>{new Date(item.viewedAt).toLocaleDateString()}</small></Link>)}</div> : <EmptyState icon={LibraryBig} title="Your research history is clear" description="Documents, lessons, and cases you open will appear here for a quick return." action={<Link to="/library" className="button button--secondary">Explore legal library</Link>} />}</section></div>

      <aside className="dashboard-aside"><section className="side-panel quick-actions"><p className="eyebrow">Quick actions</p><h2>Start a focused task</h2><Link to="/courses"><BookOpen size={19} /><span><strong>Continue a course</strong><small>Open your learning catalog</small></span><ArrowRight size={17} /></Link><Link to="/library"><FileSearch size={19} /><span><strong>Search legislation</strong><small>Filter verified records</small></span><ArrowRight size={17} /></Link><Link to="/quizzes"><FileQuestion size={19} /><span><strong>Start a quiz</strong><small>Test a completed topic</small></span><ArrowRight size={17} /></Link><Link to="/bookmarks"><Bookmark size={19} /><span><strong>Review bookmarks</strong><small>{bookmarks.length} saved item{bookmarks.length === 1 ? '' : 's'}</small></span><ArrowRight size={17} /></Link></section>
      <section className="side-panel study-goal"><Target size={22} /><p className="eyebrow">Next study goal</p>{activeCourses.length ? <><h2>Complete another lesson</h2><p>Continue {activeCourses[0].title} and keep the course moving.</p><Link to={`/courses/${activeCourses[0].id}`}>Open course <ArrowRight size={16} /></Link></> : <><h2>Choose your first milestone</h2><p>Start a course or import your institution’s verified curriculum.</p><Link to="/courses">Review courses <ArrowRight size={16} /></Link></>}</section>
      <section className="side-panel quiz-snapshot"><p className="eyebrow">Latest assessment</p>{lastQuiz ? <><strong>{lastQuiz.score}%</strong><span>{lastQuiz.quizTitle}</span><Link to="/progress">Review performance</Link></> : <><FileQuestion size={22} /><h2>No quiz attempts</h2><p>Completed assessments will build your accuracy history.</p></>}</section></aside></div>
  </div>
}
