import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Clock3, FileQuestion, RefreshCcw, RotateCcw, Target, X } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Badge, Button, EmptyState, PageHeader, ProgressBar } from '../../components/ui'
import { useData } from '../../context/DataContext'

function QuizzesPage() {
  const { data, quizHistory } = useData()
  return <div className="page"><PageHeader eyebrow="Assessments" title="Quizzes" description="Test recall, review explanations, and return to the source behind each answer." /><section className="assessment-summary"><div><FileQuestion size={22} /><span><strong>{quizHistory.length}</strong> attempts</span></div><div><Target size={22} /><span><strong>{quizHistory.length ? Math.round(quizHistory.reduce((sum, item) => sum + item.score, 0) / quizHistory.length) : 0}%</strong> average accuracy</span></div><div><Clock3 size={22} /><span><strong>{quizHistory.reduce((sum, item) => sum + Math.round((item.timeSeconds || 0) / 60), 0)}</strong> minutes assessed</span></div></section>{data.quizzes.length ? <div className="quiz-list">{data.quizzes.map((quiz) => { const attempts = quizHistory.filter((item) => item.quizId === quiz.id); const best = attempts.length ? Math.max(...attempts.map((item) => item.score)) : null; return <article key={quiz.id}><div><Badge tone="blue">{quiz.category || 'Assessment'}</Badge>{best !== null && <Badge tone="success">Best {best}%</Badge>}</div><h2>{quiz.title}</h2><p>{quiz.description || 'No assessment description supplied.'}</p><div className="meta-line"><span><FileQuestion size={15} /> {quiz.questions?.length || 0} questions</span><span><Clock3 size={15} /> {quiz.duration || 'Untimed'}</span></div><Link className="button button--primary" to={`/quizzes/${quiz.id}`}>{attempts.length ? 'Retry quiz' : 'Start quiz'} <ArrowRight size={16} /></Link></article> })}</div> : <EmptyState icon={FileQuestion} title="No assessments are available" description="The platform ships without sample questions. Import a reviewed quiz dataset from Settings when your assessments are ready." action={<Link to="/settings" className="button button--secondary">Import quiz data</Link>} />}</div>
}

function QuizRunnerPage() {
  const { quizId } = useParams()
  const { data, saveQuizAttempt } = useData()
  const quiz = data.quizzes.find((item) => item.id === quizId)
  const [index, setIndex] = useState(0)
  const [selected, setSelected] = useState(null)
  const [answers, setAnswers] = useState([])
  const [submitted, setSubmitted] = useState(false)
  const [finished, setFinished] = useState(false)
  const [saved, setSaved] = useState(false)
  const startedAt = useRef(Date.now())
  useEffect(() => () => { startedAt.current = Date.now() }, [])
  if (!quiz) return <div className="page"><EmptyState icon={FileQuestion} title="Quiz not found" description="This assessment is not available in the current catalog." action={<Link to="/quizzes" className="button button--secondary"><ArrowLeft size={16} /> All quizzes</Link>} /></div>
  if (!quiz.questions?.length) return <div className="page"><EmptyState icon={FileQuestion} title="This quiz has no questions" description="Add reviewed questions and answer explanations before assigning this assessment." action={<Link to="/quizzes" className="button button--secondary">All quizzes</Link>} /></div>
  const question = quiz.questions[index]
  const correct = selected === question.correctAnswer
  const score = Math.round((answers.filter((item) => item.correct).length / quiz.questions.length) * 100)

  function submitAnswer() { if (selected === null) return; const attempt = { questionId: question.id, selected, correct, correctAnswer: question.correctAnswer }; setAnswers((items) => [...items, attempt]); setSubmitted(true) }
  function nextQuestion() { if (index === quiz.questions.length - 1) { const finalAnswers = answers; const finalScore = Math.round((finalAnswers.filter((item) => item.correct).length / quiz.questions.length) * 100); if (!saved) { saveQuizAttempt({ id: crypto.randomUUID(), quizId: quiz.id, quizTitle: quiz.title, score: finalScore, correct: finalAnswers.filter((item) => item.correct).length, incorrect: finalAnswers.filter((item) => !item.correct).length, timeSeconds: Math.round((Date.now() - startedAt.current) / 1000), answers: finalAnswers }); setSaved(true) } setFinished(true); return } setIndex((current) => current + 1); setSelected(null); setSubmitted(false) }
  function retry() { setIndex(0); setSelected(null); setAnswers([]); setSubmitted(false); setFinished(false); setSaved(false); startedAt.current = Date.now() }

  if (finished) return <div className="page quiz-result"><Link to="/quizzes" className="back-link"><ArrowLeft size={16} /> All quizzes</Link><section><span className="result-ring" style={{ '--score': `${score * 3.6}deg` }}><strong>{score}%</strong><small>accuracy</small></span><p className="eyebrow">Assessment complete</p><h1>{quiz.title}</h1><p>{score >= 80 ? 'Strong result. Review the cited authority before moving on.' : score >= 60 ? 'A useful start. Review the explanations and revisit weaker topics.' : 'Return to the related material before another attempt.'}</p><div className="result-stats"><div><Check size={18} /><strong>{answers.filter((item) => item.correct).length}</strong><span>Correct</span></div><div><X size={18} /><strong>{answers.filter((item) => !item.correct).length}</strong><span>Incorrect</span></div><div><Clock3 size={18} /><strong>{Math.max(1, Math.round((Date.now() - startedAt.current) / 60000))}</strong><span>Minutes</span></div></div><div className="quiz-result__actions"><Button onClick={retry}><RotateCcw size={17} /> Retry quiz</Button><Link to="/progress" className="button button--secondary">View progress</Link></div></section><div className="answer-review"><p className="eyebrow">Answer review</p>{quiz.questions.map((item, itemIndex) => { const answer = answers[itemIndex]; return <article key={item.id}><span className={answer?.correct ? 'is-correct' : 'is-incorrect'}>{answer?.correct ? <Check size={16} /> : <X size={16} />}</span><div><h2>{item.prompt}</h2><p>Your answer: {answer?.selected ?? 'No answer'}</p>{!answer?.correct && <p>Correct answer: {item.correctAnswer}</p>}<small>{item.explanation || 'No explanation supplied.'}</small>{item.reference && <a href={item.reference.url} target="_blank" rel="noreferrer">Review legal reference <ArrowRight size={14} /></a>}</div></article> })}</div></div>

  return <div className="quiz-runner"><header><Link to="/quizzes"><ArrowLeft size={17} /> Exit quiz</Link><div><span>Question {index + 1} of {quiz.questions.length}</span><ProgressBar value={Math.round(((index + (submitted ? 1 : 0)) / quiz.questions.length) * 100)} /></div><Badge>{question.type || 'Multiple choice'}</Badge></header><main><p className="eyebrow">{quiz.title}</p><h1>{question.prompt}</h1>{question.scenario && <aside className="scenario"><strong>Scenario</strong><p>{question.scenario}</p></aside>}<fieldset disabled={submitted} className="answer-options"><legend className="sr-only">Choose one answer</legend>{(question.options || ['True','False']).map((option, optionIndex) => { const value = typeof option === 'string' ? option : option.value; const label = typeof option === 'string' ? option : option.label; const state = submitted && value === question.correctAnswer ? 'is-correct' : submitted && value === selected && !correct ? 'is-incorrect' : selected === value ? 'is-selected' : ''; return <label className={state} key={`${value}-${optionIndex}`}><input type="radio" name="answer" value={value} checked={selected === value} onChange={() => setSelected(value)} /><span className="option-key">{String.fromCharCode(65 + optionIndex)}</span><span>{label}</span>{submitted && value === question.correctAnswer && <Check size={18} />}{submitted && value === selected && !correct && <X size={18} />}</label> })}</fieldset>{submitted && <section className={`answer-explanation ${correct ? 'is-correct' : 'is-incorrect'}`}><div>{correct ? <Check size={19} /> : <RefreshCcw size={19} />}<strong>{correct ? 'Correct' : 'Review this point'}</strong></div><p>{question.explanation || 'No explanation has been supplied for this answer.'}</p>{question.reference && <a href={question.reference.url} target="_blank" rel="noreferrer">{question.reference.label || 'Open related legal source'} <ArrowRight size={14} /></a>}</section>}<footer>{!submitted ? <Button disabled={selected === null} onClick={submitAnswer}>Submit answer</Button> : <Button onClick={nextQuestion}>{index === quiz.questions.length - 1 ? 'See results' : 'Next question'} <ArrowRight size={17} /></Button>}</footer></main></div>
}

export default function QuizPages({ page }) {
  return page === 'quiz' ? <QuizRunnerPage /> : <QuizzesPage />
}
